name = "Traulls"
uuid = "bd9e17d5-77a1-4ac2-8218-86d07aba9392"
authors = ["Pierre Borie <pierre.borie98@gmail.com>"]
version = "1.0.0-DEV"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
ForwardDiff = "^1.0.1"
Ipopt = "^1.9.0"
JuMP = "^1.25.0"
Match = "2.4.1"
Printf = "1.11.0"
julia = "^1.11.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
